### ISSUE TITLE
can-reflect - introduction

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-reflect#1]
From https://github.com/canjs/canjs/issues/2931

Using symbols from: https://github.com/canjs/can-symbol/issues/1

- [x] - implement to the point it can be used in can-stache to improve performance by not creating computes
- [x] -  all tests pass with "happy path"
   - [x] - can-stache-bindings
   - [x] - can-component
   - [x] - can-route (using observation?)
- [x] - make can-define use this
  - [ ] - needs merging
- [x] - document
- [x] - allow Kefir observables to be directly observable
      - change guides to reflect this http://canjs.com/doc/guides/recipes/weather-report-advanced.html
- [x] - implement symbols on as many types as we can
   - [x] - can-observation
   - [x] - can-compute/proto 
   - [x] - can-compute
   - [x] - can-define w/ map and list
   - [x] - can-stache/expressions
   - [x] - can-stache-bindings
   - [x] - can-view-nodelists
   - [x] - can-map / can-list / can-map-define
- [x] - clean observation/reader
- [x] - make `can-types` use this and probably be deprecated 
- [x] - can-promise ... is value like or map like?  isResolved, state, isPending, value, error ...

**Comment by frank-dspeed** [comment]
@justinbmeyer i see you want to allow kefir to be a valid observe able can we do the same for eventEmitters as they are good observe ables :) this would make implamenting many stuff easyer
